#!/usr/bin/env bash
# Veto Messenger — Production Deploy
# Usage: bash deploy.sh <your-domain.com>
# Run as root on fresh Ubuntu 24.04

set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }
step()  { echo -e "\n${BOLD}══ $* ══${NC}"; }

DOMAIN="${1:-}"
[ -z "$DOMAIN" ] && error "Usage: bash deploy.sh <your-domain.com>"

# ── 1. Docker ─────────────────────────────────────────────────────────────────

step "Docker"
if ! command -v docker &>/dev/null; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
else
    info "Docker already installed: $(docker --version)"
fi

# ── 2. Firewall ───────────────────────────────────────────────────────────────

step "Firewall (ufw)"
if command -v ufw &>/dev/null; then
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow 22/tcp    # SSH
    ufw allow 80/tcp    # certbot ACME challenge
    ufw allow 443/tcp   # Veto Messenger
    ufw --force enable
    info "Firewall enabled: 22 (SSH), 80 (certbot), 443 (HTTPS)"
else
    apt-get install -y -qq ufw
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow 22/tcp
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw --force enable
    info "ufw installed and configured"
fi

# ── 3. Certbot + Let's Encrypt ────────────────────────────────────────────────

step "TLS Certificate (Let's Encrypt)"
if [ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    info "Installing certbot..."
    apt-get update -qq
    apt-get install -y -qq certbot

    info "Obtaining certificate for ${DOMAIN}..."
    # Port 80 must be free (no nginx/apache running yet)
    certbot certonly --standalone \
        --non-interactive \
        --agree-tos \
        --register-unsafely-without-email \
        -d "$DOMAIN"

    info "Setting up auto-renewal..."
    (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --deploy-hook 'docker compose -f /opt/veto/docker-compose.prod.yml restart server'") | crontab -
else
    info "Certificate already exists for ${DOMAIN}"
fi

CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"

# ── 3. Project directory ──────────────────────────────────────────────────────

step "Project Setup"
PROJECT_DIR="/opt/veto"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

# ── 4. .env generation ────────────────────────────────────────────────────────

step "Environment Config"
if [ ! -f .env ]; then
    POSTGRES_PASS=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
    ADMIN_TOKEN=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 48)

    cat > .env <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
POSTGRES_PASSWORD=${POSTGRES_PASS}
ADMIN_TOKEN=${ADMIN_TOKEN}

# TLS — Let's Encrypt
CERTS_DIR=${CERT_DIR}
TLS_CERT_PATH=/certs/fullchain.pem
TLS_KEY_PATH=/certs/privkey.pem

# Server listens on 443 (standard HTTPS)
BIND_PORT=443
EOF

    chmod 600 .env

    # Write credentials to a root-only file, not to terminal/history
    CREDS_FILE="/root/veto-credentials.txt"
    cat > "$CREDS_FILE" <<EOF
Veto Messenger Credentials
Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

POSTGRES_PASSWORD=${POSTGRES_PASS}
ADMIN_TOKEN=${ADMIN_TOKEN}

Admin UI: https://${DOMAIN}/admin
Health:   https://${DOMAIN}/health
EOF
    chmod 600 "$CREDS_FILE"

    info ".env created with random credentials"
    warn "Credentials saved to ${CREDS_FILE} (root-only)"
    warn "Read them with: cat ${CREDS_FILE}"
else
    info ".env already exists, skipping generation"
fi

# ── 5. docker-compose.prod.yml patch (port 443) ───────────────────────────────

step "Docker Compose Config"

# Patch port mapping to 443:3000
if grep -q '"443:3000"' docker-compose.prod.yml 2>/dev/null; then
    info "Port 443 already configured"
elif [ -f docker-compose.prod.yml ]; then
    sed -i 's|"${BIND_PORT:-3000}:3000"|"${BIND_PORT:-443}:3000"|' docker-compose.prod.yml
    info "Patched port mapping to 443"
fi

# ── 6. Build & Start ──────────────────────────────────────────────────────────

step "Build & Start"
info "Building server image (first build ~5-10 min)..."
docker compose -f docker-compose.prod.yml build --pull

info "Starting services..."
docker compose -f docker-compose.prod.yml up -d

# ── 7. Health check ───────────────────────────────────────────────────────────

step "Health Check"
info "Waiting for server..."
for i in $(seq 1 30); do
    if curl -sf "https://${DOMAIN}/health" >/dev/null 2>&1; then
        echo ""
        info "════════════════════════════════════════"
        info "  Veto Messenger is live!"
        info ""
        info "  Server URL:  https://${DOMAIN}"
        info "  Admin UI:    https://${DOMAIN}/admin"
        info "  Health:      https://${DOMAIN}/health"
        info ""
        info "  Logs: docker compose -f /opt/veto/docker-compose.prod.yml logs -f"
        info "════════════════════════════════════════"
        exit 0
    fi
    printf "."
    sleep 2
done

echo ""
error "Server not healthy. Check: docker compose -f /opt/veto/docker-compose.prod.yml logs server"
